# Generated by Django 5.0.6 on 2024-06-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapi', '0004_alter_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
