# Generated by Django 5.0.6 on 2024-06-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonapi', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images'),
        ),
    ]
